# Generated by Django 4.0.4 on 2022-05-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_description', models.CharField(max_length=255)),
                ('service_topic', models.CharField(choices=[('0', 'Web'), ('1', 'Coding')], max_length=1)),
                ('service_image', models.CharField(max_length=50)),
            ],
        ),
    ]
