# Generated by Django 4.0.4 on 2022-05-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_technology',
        ),
        migrations.AddField(
            model_name='project',
            name='project_technologies',
            field=models.ManyToManyField(to='technology.technology'),
        ),
    ]
