# Generated by Django 4.0.4 on 2022-05-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_project_project_technology_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_topic',
            field=models.CharField(choices=[('0', 'Game'), ('1', 'Code'), ('2', 'Web'), ('3', 'API')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
